### PR TITLE
Ensure `getBinary()` does not return empty string

### PR DESCRIPTION
**Pull request by rvanvelzen**
#12

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
In which situation can `PHP_BINARY` be empty?

**Comment by rvanvelzen** [comment]
See #12.

**Comment by sebastianbergmann** [comment]
#12 does not make sense to me. I neither know nor care what "arcanist" is. But if it messes with PHP then it's something that needs to be fixed. Not in PHP, not in this package, but in "arcanist".

**Comment by rvanvelzen** [comment]
I don't understand your fixation on "arcanist". I shouldn't have mentioned it since it's completely irrelevant, but I only realized that after submitting this PR.

The test script in #12 proves that `PHP_BINARY` can be the empty string, and this PR solves that issue.

**Comment by Chi-teck** [comment]
I spent a couple hours trying to find out why Drupal fails to run tests through web interface. Drupal runs test using `exec` function and it turned out that  `PHP_BINARY` was empty. That led me to this issue. The PR resolved the problem for me.

**Comment by ohthehugemanatee** [comment]
Confirming this happens for me too, running Drupal's unit tests through the web interface. So I guess that code run from exec() gets an empty PHP_BINARY value.

**Comment by ohthehugemanatee** [comment]
Thank you @sebastianbergmann !

**Pull request merged**
